pyuic5 -x "designer/MainWindow.ui" -o "src/ui/MainWindow.py"
pyuic5 -x "designer/login.ui" -o "src/ui/login.py"
pyuic5 -x "designer/systemadmin.ui" -o "src/ui/systemadmin.py"
pyuic5 -x "designer/systemalu.ui" -o "src/ui/systemalu.py"
pyuic5 -x "designer/systemprofe.ui" -o "src/ui/systemprofe.py"
echo "DONE"