# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setEnabled(True)
        Login.resize(400, 450)
        Login.setMinimumSize(QtCore.QSize(400, 450))
        Login.setMaximumSize(QtCore.QSize(400, 450))
        font = QtGui.QFont()
        font.setItalic(False)
        Login.setFont(font)
        Login.setStyleSheet("QWidget#centralwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.531, y1:0.977273, x2:0, y2:0, stop:0 rgba(59, 125, 189, 255), stop:1 rgba(255, 255, 255, 255));}")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 40, 197, 33))
        self.label.setMaximumSize(QtCore.QSize(197, 33))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(19)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color: black;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 55, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(55, 21))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.input_legajo = QtWidgets.QLineEdit(self.centralwidget)
        self.input_legajo.setGeometry(QtCore.QRect(130, 160, 181, 21))
        self.input_legajo.setStyleSheet("border-radius: 5px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(88, 145, 255, 255));")
        self.input_legajo.setObjectName("input_legajo")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(24, 200, 101, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.input_pass = QtWidgets.QLineEdit(self.centralwidget)
        self.input_pass.setGeometry(QtCore.QRect(130, 200, 181, 21))
        self.input_pass.setStyleSheet("border-radius: 5px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(88, 145, 255, 255));")
        self.input_pass.setDragEnabled(False)
        self.input_pass.setPlaceholderText("")
        self.input_pass.setObjectName("input_pass")
        self.btn_login = QtWidgets.QPushButton(self.centralwidget)
        self.btn_login.setGeometry(QtCore.QRect(130, 300, 131, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_login.sizePolicy().hasHeightForWidth())
        self.btn_login.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        self.btn_login.setFont(font)
        self.btn_login.setToolTipDuration(-1)
        self.btn_login.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_login.setStyleSheet("border-radius: 8px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(10, 155, 245, 255));\n"
"")
        self.btn_login.setText("Ingresar")
        self.btn_login.setCheckable(False)
        self.btn_login.setObjectName("btn_login")
        self.btn_salir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_salir.setGeometry(QtCore.QRect(300, 410, 81, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_salir.sizePolicy().hasHeightForWidth())
        self.btn_salir.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.btn_salir.setFont(font)
        self.btn_salir.setToolTipDuration(-1)
        self.btn_salir.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_salir.setStyleSheet("border-radius: 8px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(10, 155, 245, 255));")
        self.btn_salir.setText("Salir")
        self.btn_salir.setCheckable(False)
        self.btn_salir.setObjectName("btn_salir")
        self.label_error = QtWidgets.QLabel(self.centralwidget)
        self.label_error.setGeometry(QtCore.QRect(70, 250, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(10)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color:red;")
        self.label_error.setText("")
        self.label_error.setObjectName("label_error")
        Login.setCentralWidget(self.centralwidget)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "MainWindow"))
        self.label.setText(_translate("Login", "INICIAR SESIÓN"))
        self.label_2.setText(_translate("Login", "Legajo:"))
        self.label_3.setText(_translate("Login", "Contraseña:"))
        self.btn_login.setToolTip(_translate("Login", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.btn_login.setWhatsThis(_translate("Login", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.btn_salir.setToolTip(_translate("Login", "<html><head/><body><p align=\"right\"><br/></p></body></html>"))
        self.btn_salir.setWhatsThis(_translate("Login", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
