# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/systemalu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Systemalu(object):
    def setupUi(self, Systemalu):
        Systemalu.setObjectName("Systemalu")
        Systemalu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Systemalu)
        self.centralwidget.setObjectName("centralwidget")
        Systemalu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Systemalu)
        QtCore.QMetaObject.connectSlotsByName(Systemalu)

    def retranslateUi(self, Systemalu):
        _translate = QtCore.QCoreApplication.translate
        Systemalu.setWindowTitle(_translate("Systemalu", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Systemalu = QtWidgets.QMainWindow()
    ui = Ui_Systemalu()
    ui.setupUi(Systemalu)
    Systemalu.show()
    sys.exit(app.exec_())
