# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/system.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_System(object):
    def setupUi(self, System):
        System.setObjectName("System")
        System.resize(560, 394)
        self.centralwidget = QtWidgets.QWidget(System)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btn_logout = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_logout.setFont(font)
        self.btn_logout.setObjectName("btn_logout")
        self.gridLayout_2.addWidget(self.btn_logout, 1, 0, 1, 1)
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(12)
        self.label_info.setFont(font)
        self.label_info.setText("")
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.gridLayout_2.addWidget(self.label_info, 0, 0, 1, 1)
        System.setCentralWidget(self.centralwidget)

        self.retranslateUi(System)
        QtCore.QMetaObject.connectSlotsByName(System)

    def retranslateUi(self, System):
        _translate = QtCore.QCoreApplication.translate
        System.setWindowTitle(_translate("System", "MainWindow"))
        self.btn_logout.setText(_translate("System", "Cerrar Sesión"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    System = QtWidgets.QMainWindow()
    ui = Ui_System()
    ui.setupUi(System)
    System.show()
    sys.exit(app.exec_())
