# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/systemalu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Systemalu(object):
    def setupUi(self, Systemalu):
        Systemalu.setObjectName("Systemalu")
        Systemalu.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Systemalu)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(11)
        self.label_info.setFont(font)
        self.label_info.setAlignment(QtCore.Qt.AlignCenter)
        self.label_info.setObjectName("label_info")
        self.gridLayout.addWidget(self.label_info, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.btn_logout_alu = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_logout_alu.setFont(font)
        self.btn_logout_alu.setObjectName("btn_logout_alu")
        self.gridLayout.addWidget(self.btn_logout_alu, 2, 0, 1, 1)
        Systemalu.setCentralWidget(self.centralwidget)

        self.retranslateUi(Systemalu)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Systemalu)

    def retranslateUi(self, Systemalu):
        _translate = QtCore.QCoreApplication.translate
        Systemalu.setWindowTitle(_translate("Systemalu", "MainWindow"))
        self.label_info.setText(_translate("Systemalu", "Logeado como"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Systemalu", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Systemalu", "Tab 2"))
        self.btn_logout_alu.setText(_translate("Systemalu", "Cerrar sesión"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Systemalu = QtWidgets.QMainWindow()
    ui = Ui_Systemalu()
    ui.setupUi(Systemalu)
    Systemalu.show()
    sys.exit(app.exec_())
