# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/systemprofe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Systemprofe(object):
    def setupUi(self, Systemprofe):
        Systemprofe.setObjectName("Systemprofe")
        Systemprofe.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Systemprofe)
        self.centralwidget.setObjectName("centralwidget")
        Systemprofe.setCentralWidget(self.centralwidget)

        self.retranslateUi(Systemprofe)
        QtCore.QMetaObject.connectSlotsByName(Systemprofe)

    def retranslateUi(self, Systemprofe):
        _translate = QtCore.QCoreApplication.translate
        Systemprofe.setWindowTitle(_translate("Systemprofe", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Systemprofe = QtWidgets.QMainWindow()
    ui = Ui_Systemprofe()
    ui.setupUi(Systemprofe)
    Systemprofe.show()
    sys.exit(app.exec_())
